### ISSUE TITLE
Colors appear different on the same file in VSCode vs Doom Emacs

### ISSUE THREAD

**Issue by JJGadgets** [helderburato/doom-emacs#1]
> If you're reporting an UI issue, make sure you take a screenshot that shows the actual bug.

My VS Code using the official Dracula theme is more vibrant than the doom-dracula theme in Doom Emacs, when displaying the same JavaScript file. Is this normal, or a configuration error on my part? 
I'm using GCC Emacs 28.5.0.

![image](https://user-images.githubusercontent.com/5709019/116018887-95d3c400-a675-11eb-9408-ce555c1cd53a.png)

**Comment by helderberto** [comment]
Hi, @JJGadgets, if I remember well, at VSCode, do you have three options for Dracula scheme. What are you using on this screenshot?

**Comment by JJGadgets** [comment]
> Hi, @JJGadgets, if I remember well, at VSCode, do you have three options for Dracula scheme. What are you using on this screenshot?

I am using just Dracula. 

``”workstation.colorTheme”: “Dracula”``

I think it has something to do with (my?) Doom Emacs not highlighting whatever *is* highlighted brightly in VSCode.

**Comment by helderberto** [comment]
You can read all the configs about Doom Emacs with Dracula [here](https://github.com/hlissner/emacs-doom-themes/blob/master/themes/doom-dracula-theme.el).
